import { createRoutesFromChildren } from "react-router-dom";
import Invoice from "../features/forecastpo/pages/Invoice";

export const tableContent = {
  vendorId: "Vendor ID",
  vendorName: "Vendor Name",
  state : "State",
  vendorContact: "Vendor Contact",
  orderNo: "Order No",
  orderPrice: "Order Price",
  orderDate: "Order Date",
  location: "Location",
  address : "Address",
  status: "Status",
  more: "More",
  returnDate: "Return Date",
  returnValue: "Return Value",
  nodata: "No Data Available",
  partName: "Part Name",
  ptg: "PTG Part No.",
  mfNo: "Manufacturer Part No",
  qty: "Quantity",
  actions: "Actions",
  clientId: "Client ID",
  clientName: "Client Name",
  typesofBOMs: "No.of BOM's",
  contactDetails: "Contact Details",
  email: "Email",
  bomId: "Bom ID",
  bomName: "Bom Name",
  categories: "Categories",
  moq: "Moq",
  warranty: "Warranty(yrs)",
  leadTime: "Lead Time(wks)",
  Price: "Price",
  GST: "GST %",
  contact: "Contact No",
  clientCreatedDate: "Client Created Date",
  prodType: "Product Types",
  components: "Components",
  
};

export const vendorListTable = {
  //vendor list page  //
  listofVendors: "List of Vendors",
  allVendors: "All Vendors",
  mcatVendors: "M - Vendors",
  ecatVendors: "E - Vendors",
  meCatVendors: "M & E - Vendors",
};
export const textToast = {
  //strings that are displayed //
  deletetext: " Are you sure you want to delete? ",
  noData: "No Data Available",
  actTOinact: "Are you sure want to move to Inactive ?",
  inactTOact: "Are you sure want to move to Active ?",
  noDoc: "No Documents Available.",
  maxlength: "(max 500 characters)",
  approvedtext: "Are you sure you want to confirm ?",
  approvedCancle: "Are you sure you want to cancel ?",
};
export const formFieldsVendor = {
  // add partner/vendor form //
  createFormHeaderP: "Create Partner",
  createFormHeaderV: "Create Vendor",
  FormSubHeaderP: "Partner Info",
  FormSubHeaderV: "Vendor Info",
  vendorType: "Vendor Type",
  selectVendor: " Select vendor",
  mCat: "M-Category",
  eCat: "E-Category",
  emCat: "M & E-Category",
  partnersCat: "Partners",
  partnerName: "Partner Name",
  partnerDate: "Partner Date",
  vendorName: "Vendor Name",
  contactnum: "Contact Number",
  email: "Email",
  address1: "Address 1",
  address2: "Address 2",
  landmark: "Landmark",
  cityName: "City Name",
  pinCode: "Pincode",
  country: "Country",
  state: "State",
  gstNumber: "GST Number",
  panNumber: "PAN Number",
  partnerType: "Select Type",
  partnertype: "Partner Type",
  ems: "EMS",
  boxBuilding: "BOX BUILDING",
  contactInfo: "Contact Info",
  pointofContactName: "PTG POC name",
  pointofContactNum: "PTG POC contact Number",
  vendorPointofContactName: "Vendor POC name",
  vendorPointofContactNum: "Vendor POC contact Number",
  partnerPocName : "Partner POC Name",
  partnerPocContact : "Partner POC Contact Number",
  reciever: "Reciever",
  recieverContact: "Contact( Reciever )",
  bankInfo: "Bank Info",
  holderName: "Name",
  bankName: "Bank Name",
  ACnum: "Account Number",
  ifscCode: "IFSC Code",
  branchName: "Branch Name",
  otherInfo: "Other Info",
  categoryInfo: "Category Info",
  terms: "Terms & Conditions",
  payment: "Custom Payment",
  documentsTitle: "Registration Documents",
  titlePdf: "Documents",
  documents: "Attach Documents",
  btnCreate: "Create",
  btnCancel: "Cancel",
  btnSend:"Send",
  btnUpdate: "Update",
  loader: "Loading...",
  btnAssign:"Assign",

  //    edit partner/vendor form //
  editPartner: "Edit Partner",
  editVendor: "Edit Vendor",

  //vendors partner details page//
  download: "Download partner details",
  partnerID: "Partner ID",
  contact: "Contact",
  sno: "S.No",
  orderId: "Order ID",
  orderDate: "Order Date",
  paymentTerms: "Payment Terms",
  productsCount: "No of Products",
  orderValue: "Order Value",
  bomId: "BOM ID",
  boardsQty: "Boards Quantity",
  material: "Material Percentage",
  manufactnum: "Manufacturer Part No",
};

export const tableBOM = {
  //add bom page //
  addBomTitle: "Adding BOM",
  bomInfo: "BOM Info",
  mountingType: "Mounting Type",
  qtyPerBoard: "Qty Per Board",
  deviceCat: "Category",
  subCategory: "Sub Category",
  mfrPartNo: "Manufacturer Part No",
  description: "Description",
  technicalDetails: "Technical Details",
  category: "Category",
  prodName: "Product Name",
  vicNo: "VIC Part No",
  bomName: "BOM Name",
  bomInfo: "BOM Info",
  prtNo :" Part No",
  pckng :"Packing",
  footPrint : "Foot Print",
  HSNCODE : "HSN Code",
  partName : "Part Name",

  // edit bom page//
  bomID: "BOM ID",
  editBOM: "Edit BOM",
  date: "Date",
  partnerType : "Partner Type",

  //ptgnodetails //
  material: "Material",
  Mftr: "Manufacturer",
  reqQty: "Required Quantity",
  estMaterials: "Estimate materials",

  // original partno details //
  mfPrtno: "Manufacturer Part No",
  outwardId: "Outward ID",
  partnerId: "Partner ID",
  outwardDate: "Outward Date",
  boardsQty: "Boards Quantity",
  mtrlpercentage: "Material Percentage",

  // outward details page//
  providedQty: "Provided Qty",
  blncQty: "Balance Qty",
  batchno: "Batch.No",
  damageQty:"Damage Qty",

  // client page //
  assignHeader:"Assigning to Client",
  assignSubHeader: "Details",
  selectClient:"Select Client",
  againstPO:"Against PO",
  senderName:"Sender Name",
  senderCnt:"Sender Contact",
  receiverName:"Receiver Name",
  receiverCntNum:"Receiver Contact Number",
  receiverCnt :"Receiver Contact",
  DED:" Delivery End Date",

  //send kit //
  sendKit:" Send Kit",
  details:"Details",
  headerComponentsList:"Components List"
};

export const ordersTable = {
  Sno : "S.No",
  bomId : "Bom ID",
  poId : "PO ID",
  description: "Description",
  unit : "Unit",
  rate : "Rate",
  discount : "Discount",
  basicAmount : "Basic Amount",
  pdf: "Download as Pdf",
  paymentText : "Payment Terms",
  termsText : "Terms & Conditions"

}

export const buttonTexts = {
  create : "Create",
  cancel : "Cancel",
  update : "Update",
  send: "Send",
  markUpdate : "Mark as update Return",
  markReturn : "Mark as Return",
}

export const clientForm = {
 cInfo : "Client Info",
 cName : "Client Name",
 cLocation : "Client Location",
 cCno : "Contact Number",
 otherInfo : "Other Info",
 paymentText : "Payment Terms",
 termsText : "Terms & Conditions",
 rDocuments : "Registration Documents",
 aDocuments : "Attach Documents",
 loaderText : "Loading.."
}

export const gateEntryTable = {
  sNo : "S.No",
  partNo : "Part No",
  partName : "Part Name",
  manufacturer : "Manufacturer",
  description : "Description",
  packaging : "Packaging",
  quantity : "Quantity",
  pass_qty : "Pass Qty",
  fail_qty : "Fail Qty",
  inventory_position : "Inventory position",
  batch_no : "Batch No",
  passQuantity : "Pass Qty"
}
export const sendBoardsText ={
  downloadCsvFormat : "Download Csv Format",
  details : "Details",
  deliveryEndDate : "Delivery End Date",
  csvFile: "Drag and drop to upload your CSV File",
  bInfo : "Boards Info",
  svicPcba : "SVIC PCBA",
  somID : "SOM ID/IMEI ID",
  eSimID : "E SIM ID",
  alsPcba : "ALS PCBA",
  displayNo : "Display Number",
  eSimNo : "E SIM No",
  preview : "Preview of Uploaded CSV Data",
  finalInfo:"Final Info"

}

export const returnPOText = {
  total : "Total",
  sno : "S.No",
  status : "Status",
  pricePiece : "Price Per Piece",
  price : "Price",
  qty : "Quantity",
  packaging : "Packaging",
  desc : "Description",
  manufacturer : "Manufacturer",
  partName : "Part Name",
  mPartno: "Manufacturer Part No",
  uploadPhoto : "Upload Photo",
  qaTextdoc : "QA Test Document",
  uploadInvoice : "Upload Invoice",
  status : "Status",
  sendcontactNumber : "Sender Contact Number",
  senderName : "Sender Name",
  qaDate : "QA Date",
  orderId : "Order ID",
  inwardId : "Inward ID",
  orderDetails : "Order Details",


}

export const createclientforecastPOText = {
buyerDetails : "Buyer Details",
deliveryLocation : "Delivery Location",
supplierDetails : "Supplier Details",
placeofSupply : "Place Of Supply ",
FormSubHeaderC:  "Primary Document Details", 
documentTitle : "Document Title",
documentdate : "Document Date",
status : "Status",
deliveryDate : "Delivery Date",
clientName : "Client Name",
bomNames : "Bom Names",
paymentTerms : "Payment Terms",
FormSubHeadePL : "Adding products to purchase list",
sNo : "S.No",
itemNo : "Item No",
hsnsaccode : "HSN/SAC Code",
deliveryDate : "Delivery Date",
qty : "Qty",
unit : "Unit",
rate : "Rate",
gst : "Gst(%)",
total : "Total",
FormSubHeadeTM:"Total Amount",
totalbeforetax : "Total(before tax) ",
totalTaxGST  : "Total Tax(IGST)",
totalaftertax: "Total(after tax)",
FormSubHeadeGT : "Grand Total",
advanceTopay : "Advance to pay",
balanceTopay : "Balance to pay",

}

export const salesTable = {
 sNo : "S.No",
 companyName : " Company Name",
 transactionName : " Transaction Name",
 documentNumber : " Document Number",
 bomName : "Bom name",
 dueDate : "Due Date",
 status : "Status",
 lastDuedate :" Last Due Date",
 actions : "Actions",

}
export const createdpoform ={
  cpo : "Create Purchase Order",
  KindAttn : "Kind Attn",
  CompanyName:"Company Name",
  GSTNo:"GST No",
  PanNo:"Pan No",
  ContactDetails :"Contact Details",
  PhoneNo:"Phone No",
  ShipTo:"Ship To",
  poTerms:"Po Terms & Conditions",
  RequestLine:"Request Line",
  PrimaryDocumentDetails:"Primary Document Details",
  TransactionName:"Transaction Name",
  PODate:"PO Date",
  AmendmentNo:"Amendment No",
  AmendmentDate:"Amendment Date",
  QuoteReference :"Quote Reference",
  QuoteDate :"Quote Date",
  BuyerCode:"Buyer Code",
  Currency:"Currency",
  ClientPo:"Client Po",
  Add :"+ Add",
  Addingproductstopurchaselist:"Adding products to purchase list",
  SNo:"S.No",
  ItemNo:"Item No.",
  Rev:"Rev.",
  desc:"Description ( HSN / SAC )",
  DeliveryDate:"Delivery Date",
  Qty:"Qty",
  Unit:"Unit",
  Rate:"Rate",
  BasicAmount:"Basic Amount",
  GST:"GST",
  Actions:"Actions",
  TotalAmount:"Total Amount",
  TotalBasic:"Total( Basic )",
  TotalGST:"Total GST",
  ShippingCharges:"Shipping Charges",
  GrandTotal:"Grand Total",
  AmountInWords:"Amount In Words",
  SecondaryDocumentDetails:"Secondary Document Details",
  PreparedBy:"Prepared By",
  CheckedBy:"Checked By",
  AuthorizedSignatory:"Authorized Signatory",
  Note:"Note",
  terms:"Terms & Conditions",
  Create:"Create",
  SaveAsDraft:"Save As Draft",
  piTerms:"PI Terms & Conditions",
  PIDate:"PI Date",
}

export const  approvaltab = {
 sNo : "S.No",
 documentNumber : " Document Number",
 companyName : " Company Name",
 transactionName : " Transaction Name",
 creationdate:"Creation Date",
 dueDate : "Due Date",
 amount:"Amount",
 status : "Status",
 actions : "Actions",
 lastDateModified:"Last Date Modified"

}
export const invoiceform ={
  inv : "Invoice",
  KindAttn : "Kind Attn",
  CompanyName:"Company Name",
  GSTNo:"GST No",
  PanNo:"Pan No",
  ContactDetails :"Contact Details",
  PhoneNo:"Phone No",
  StateName:"State Name",
  StateCode:"State Code",
  //Buyer:"Buyer",
  ShipTo:"Ship To",
  poTerms:"Po Terms & Conditions",
  RequestLine:"Request Line",
  PrimaryDocumentDetails:"Primary Document Details",
  TransactionName:"Transaction Name",
  InvoiceDate:" Invoice Date",
  InvoiceNo:"Invoice No",
  AmendmentNo:"Amendment No",
  AmendmentDate:"Amendment Date",
  QuoteReference :"Quote Reference",
  QuoteDate :"Quote Date",
  BuyerCode:"Buyer Code",
  Currency:"Currency",
  ClientPo:"Client Po",
  PoNo:"PO NO",
  Add :"+ Add",
  Addingproductstopurchaselist:"Adding products to purchase list",
  SNo:"S.No",
  ItemNo:"Item No.",
  Rev:"Rev.",
  desc:"Description ( HSN / SAC )",
  DeliveryDate:"Delivery Date",
  Qty:"Qty",
  Unit:"Unit",
  Rate:"Rate",
  BasicAmount:"Basic Amount",
  GST:"GST",
  Actions:"Actions",
  TotalAmount:"Total Amount",
  TotalBasic:"Total( Basic )",
  TotalGST:"Total GST",
  ShippingCharges:"Shipping Charges",
  FreightCharges:"Freight Charges",
  GrandTotal:"Grand Total",
  AmountInWords:"Amount In Words",
  SecondaryDocumentDetails:"Secondary Document Details",
  PreparedBy:"Prepared By",
  CheckedBy:"Checked By",
  AuthorizedSignatory:"Authorized Signatory",
  Note:"Note",
  terms:"Terms & Conditions",
  Create:"Create",
  SaveAsDraft:"Save As Draft"
}

export const ProformaINvoice = {
  Update: "Update",
  Cancel: "Cancel"
}